name: Build and Deploy to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Installing pandoc is done this way instead of with the package manager because the version
      # on apt is just too old
      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb
          sudo dpkg -i pandoc-2.18-1-amd64.deb

      - name: Install premailer
        run: pip3 install --user premailer

      - name: Convert all markdown to HTML
        run: bash ${{ github.workspace }}/build/build_all.sh -v

      # The build output is uploaded to an artifact so it can then be downloaded by the deploy job
      - name: Upload files
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: output
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/out/

          # The desired behavior if no files are found using the provided path.
          # warn: Output a warning but do not fail the action
          # error: Fail the action with an error message
          # ignore: Do not output any warnings or errors, the action does not fail
          # if-no-files-found: warn

          # Duration after which artifact will expire in days. 0 means using default retention.
          # Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
          # retention-days:

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download a build artifact
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: output
          # Destination path
          path: out

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          # This is the branch you wish to deploy to.
          branch: gh-pages
          # The folder in your repository that you want to deploy. If your build script compiles into a directory named build you would put it here. Folder paths cannot have a leading / or ./. If you wish to deploy the root directory you can place a . here.
          folder: out

          # If you would like to push the contents of the deployment folder into a specific directory on the deployment branch you can specify it here.
          # target-folder:

          # If you need to customize the commit message for an integration you can do so.
          # commit-message:
